-- init_indicator_data.sql
-- TECHNICAL_INDICATOR + INDICATOR_CURSOR 시드 데이터
-- 전제: init_data.sql 이 먼저 실행되어 DAILY_STOCK_PRICE 데이터가 있어야 함
-- 제외 지표 (252행 필요): HIGH_20D_RATIO, HIGH_52W_RATIO, IS_52W_HIGH/LOW, IS_20D_HIGH/LOW
--
-- 모든 INDICATOR_NAME 값은 Java enum IndicatorType 이름과 정확히 일치해야 함.
-- (@Enumerated(EnumType.STRING) 사용)
SET NAMES utf8mb4;
USE DOVE_STOCK;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE TECHNICAL_INDICATOR;
TRUNCATE TABLE INDICATOR_CURSOR;
SET FOREIGN_KEY_CHECKS = 1;

-- ─────────────────────────────────────────
-- 1. SMA (단순이동평균)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4   PRECEDING AND CURRENT ROW) AS sma5,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 9   PRECEDING AND CURRENT ROW) AS sma10,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19  PRECEDING AND CURRENT ROW) AS sma20,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 49  PRECEDING AND CURRENT ROW) AS sma50,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 59  PRECEDING AND CURRENT ROW) AS sma60,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS sma120,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS sma200
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_5',   sma5,   NOW() FROM base WHERE rn >= 5   UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_10',  sma10,  NOW() FROM base WHERE rn >= 10  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_20',  sma20,  NOW() FROM base WHERE rn >= 20  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_50',  sma50,  NOW() FROM base WHERE rn >= 50  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_60',  sma60,  NOW() FROM base WHERE rn >= 60  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_120', sma120, NOW() FROM base WHERE rn >= 120 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_200', sma200, NOW() FROM base WHERE rn >= 200;

-- ─────────────────────────────────────────
-- 2. EMA (지수이동평균, SMA 근사)
--    실제 EMA 대신 SMA로 근사 (시드 데이터 목적)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4   PRECEDING AND CURRENT ROW) AS ema5,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 9   PRECEDING AND CURRENT ROW) AS ema10,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19  PRECEDING AND CURRENT ROW) AS ema20,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 59  PRECEDING AND CURRENT ROW) AS ema60,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS ema120,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS ema200
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_5',   ema5,   NOW() FROM base WHERE rn >= 5   UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_10',  ema10,  NOW() FROM base WHERE rn >= 10  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_20',  ema20,  NOW() FROM base WHERE rn >= 20  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_60',  ema60,  NOW() FROM base WHERE rn >= 60  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_120', ema120, NOW() FROM base WHERE rn >= 120 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_200', ema200, NOW() FROM base WHERE rn >= 200;

-- ─────────────────────────────────────────
-- 3. Stochastic %K/%D
--    %K = (close - MIN_LOW_14) / (MAX_HIGH_14 - MIN_LOW_14) * 100
--    %D = AVG(K, 7)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS low14,
         MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS high14
  FROM DAILY_STOCK_PRICE
),
stoch AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN high14 = low14 THEN 50.0
              ELSE (CLOSE_PRICE - low14) / (high14 - low14) * 100
         END AS k_raw
  FROM base
),
with_d AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, k_raw,
         AVG(k_raw) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS d_raw
  FROM stoch
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_K_14_7', k_raw, NOW() FROM with_d WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_D_14_7', d_raw, NOW() FROM with_d WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 4. Bollinger Bands
--    BB_MIDDLE = SMA20, BB_UPPER = SMA20 + 2*STDDEV20, BB_LOWER = SMA20 - 2*STDDEV20
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         AVG(CLOSE_PRICE)        OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mid,
         STDDEV_POP(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sd
  FROM DAILY_STOCK_PRICE
),
bb AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, CLOSE_PRICE, mid,
         mid + 2 * sd AS upper_b,
         mid - 2 * sd AS lower_b
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_UPPER_20',     upper_b,                                                                            NOW() FROM bb WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_MIDDLE_20',    mid,                                                                                 NOW() FROM bb WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_LOWER_20',     lower_b,                                                                             NOW() FROM bb WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_PERCENT_B_20', CASE WHEN upper_b = lower_b THEN 0.5 ELSE (CLOSE_PRICE - lower_b) / (upper_b - lower_b) END, NOW() FROM bb WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_WIDTH_20',     upper_b - lower_b,                                                                   NOW() FROM bb WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 5. CCI
--    TP = (HIGH + LOW + CLOSE) / 3
--    CCI = (TP - SMA_TP_20) / (0.015 * mean_abs_dev_20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 AS tp
  FROM DAILY_STOCK_PRICE
),
sma_tp AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, tp,
         AVG(tp) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma_tp
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'CCI',
       (tp - sma_tp) / NULLIF(
         0.015 * AVG(ABS(tp - sma_tp)) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW),
         0
       ),
       NOW()
FROM sma_tp WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 6. Williams %R
--    %R = (MAX_HIGH_14 - close) / (MAX_HIGH_14 - MIN_LOW_14) * -100
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS high14,
         MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS low14
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'WILLIAMS_R',
       CASE WHEN high14 = low14 THEN -50.0
            ELSE (high14 - CLOSE_PRICE) / (high14 - low14) * -100
       END,
       NOW()
FROM base WHERE rn >= 14;

-- ─────────────────────────────────────────
-- 7. OBV (On-Balance Volume)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         CLOSE_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
),
signed_vol AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN prev_close IS NULL THEN 0
              WHEN CLOSE_PRICE > prev_close THEN  VOLUME
              WHEN CLOSE_PRICE < prev_close THEN -VOLUME
              ELSE 0
         END AS svol
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'OBV',
       SUM(svol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
       NOW()
FROM signed_vol WHERE rn >= 2;

-- ─────────────────────────────────────────
-- 8. Volume Ratio (20)
--    (up_vol + unchanged_vol/2) / (down_vol + unchanged_vol/2) * 100
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         CLOSE_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
),
tagged AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN CLOSE_PRICE > prev_close THEN VOLUME ELSE 0 END AS up_vol,
         CASE WHEN CLOSE_PRICE < prev_close THEN VOLUME ELSE 0 END AS dn_vol,
         CASE WHEN CLOSE_PRICE = prev_close THEN VOLUME ELSE 0 END AS eq_vol
  FROM base WHERE prev_close IS NOT NULL
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_RATIO_20', vr, NOW()
FROM (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         (SUM(up_vol) OVER w + SUM(eq_vol) OVER w / 2.0)
         / NULLIF(SUM(dn_vol) OVER w + SUM(eq_vol) OVER w / 2.0, 0) * 100 AS vr
  FROM tagged
  WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW)
) t WHERE rn >= 21 AND vr IS NOT NULL;

-- ─────────────────────────────────────────
-- 9. Volume MA20 Ratio
--    volume / AVG(volume, 20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         AVG(VOLUME) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS vol_ma20
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_MA20_RATIO',
       VOLUME / NULLIF(vol_ma20, 0),
       NOW()
FROM base WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 10. Gap Open
--     (open / prev_close) - 1.0
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         OPEN_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'GAP_OPEN',
       OPEN_PRICE / NULLIF(prev_close, 0) - 1.0,
       NOW()
FROM base WHERE rn >= 2;

-- ─────────────────────────────────────────
-- 11. Volatility (log return STDDEV)
--     VOLATILITY_5D  = STDDEV(log daily return, 5)
--     VOLATILITY_20D = STDDEV(log daily return, 20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         LN(CLOSE_PRICE / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE), 0)) AS log_ret
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_5D',
       STDDEV_POP(log_ret) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4  PRECEDING AND CURRENT ROW),
       NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_20D',
       STDDEV_POP(log_ret) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW),
       NOW() FROM base WHERE rn >= 21;

-- ─────────────────────────────────────────
-- 12. RSI (SMA 근사)
--     avg_gain = AVG(MAX(close-prev,0), N)
--     RSI = 100 - 100 / (1 + avg_gain/avg_loss)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         GREATEST(CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE), 0) AS gain,
         GREATEST(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) - CLOSE_PRICE, 0) AS loss
  FROM DAILY_STOCK_PRICE
),
rsi AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8  PRECEDING AND CURRENT ROW) AS ag9,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8  PRECEDING AND CURRENT ROW) AS al9,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS ag14,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS al14,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) AS ag21,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) AS al21
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_9',  CASE WHEN al9=0  THEN 100 ELSE 100-100/(1+ag9/al9)   END, NOW() FROM rsi WHERE rn >= 45  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_14', CASE WHEN al14=0 THEN 100 ELSE 100-100/(1+ag14/al14) END, NOW() FROM rsi WHERE rn >= 70  UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_21', CASE WHEN al21=0 THEN 100 ELSE 100-100/(1+ag21/al21) END, NOW() FROM rsi WHERE rn >= 105;

-- ─────────────────────────────────────────
-- 16. ATR (Average True Range, SMA 근사)
--     TR = MAX(high-low, |high-prevClose|, |low-prevClose|)
--     ATR = AVG(TR, 14)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         GREATEST(
           HIGH_PRICE - LOW_PRICE,
           ABS(HIGH_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE)),
           ABS(LOW_PRICE  - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE))
         ) AS tr
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ATR',
       AVG(tr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW),
       NOW()
FROM base WHERE rn >= 70;

-- ─────────────────────────────────────────
-- 17. MFI (Money Flow Index)
--     TP = (H+L+C)/3, RMF = TP * volume
--     MFI = 100 - 100 / (1 + pos_flow/neg_flow)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 AS tp,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 * VOLUME AS rmf,
         LAG((HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_tp
  FROM DAILY_STOCK_PRICE
),
flows AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN tp > prev_tp THEN rmf ELSE 0 END AS pos_mf,
         CASE WHEN tp < prev_tp THEN rmf ELSE 0 END AS neg_mf
  FROM base WHERE prev_tp IS NOT NULL
),
mfi_raw AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         SUM(pos_mf) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS pos_sum,
         SUM(neg_mf) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS neg_sum
  FROM flows
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MFI',
       CASE
         WHEN neg_sum = 0 AND pos_sum = 0 THEN 50.0
         WHEN neg_sum = 0 THEN 100.0
         ELSE 100 - 100 / (1 + pos_sum / neg_sum)
       END,
       NOW()
FROM mfi_raw WHERE rn >= 15;

-- ─────────────────────────────────────────
-- 18. MACD (SMA 근사: EMA12≈SMA12, EMA26≈SMA26, signal=SMA9(MACD))
--     MACD_LINE      = SMA12 - SMA26
--     MACD_SIGNAL    = SMA9(MACD_LINE)
--     MACD_HISTOGRAM = MACD_LINE - MACD_SIGNAL
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS sma12,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 25 PRECEDING AND CURRENT ROW) AS sma26
  FROM DAILY_STOCK_PRICE
),
macd_line AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, sma12 - sma26 AS macd FROM base
),
macd_sig AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, macd,
         AVG(macd) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8 PRECEDING AND CURRENT ROW) AS sig
  FROM macd_line
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_LINE',      macd,        NOW() FROM macd_sig WHERE rn >= 130 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_SIGNAL',    sig,         NOW() FROM macd_sig WHERE rn >= 130 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_HISTOGRAM', macd - sig,  NOW() FROM macd_sig WHERE rn >= 130;

-- ─────────────────────────────────────────
-- 19. ADX_14 / PLUS_DI_14 / MINUS_DI_14 (SMA 근사)
--     +DI = 100 * AVG(+DM,14) / AVG(TR,14)
--     -DI = 100 * AVG(-DM,14) / AVG(TR,14)
--     ADX = AVG(DX, 14),  DX = 100 * |+DI - -DI| / (+DI + -DI)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         HIGH_PRICE AS h, LOW_PRICE AS l, CLOSE_PRICE AS c,
         LAG(HIGH_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS ph,
         LAG(LOW_PRICE)   OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS pl,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS pc
  FROM DAILY_STOCK_PRICE
),
dm AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         GREATEST(h - l, ABS(h - pc), ABS(l - pc)) AS tr,
         CASE WHEN (h - ph) > (pl - l) AND (h - ph) > 0 THEN h - ph ELSE 0 END AS pdm,
         CASE WHEN (pl - l) > (h - ph) AND (pl - l) > 0 THEN pl - l ELSE 0 END AS ndm
  FROM base WHERE pc IS NOT NULL
),
di AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         100 * AVG(pdm) OVER w / NULLIF(AVG(tr) OVER w, 0) AS pdi,
         100 * AVG(ndm) OVER w / NULLIF(AVG(tr) OVER w, 0) AS ndi
  FROM dm
  WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
),
dx AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, pdi, ndi,
         100 * ABS(pdi - ndi) / NULLIF(pdi + ndi, 0) AS dx
  FROM di
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ADX_14',
       AVG(dx) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW),
       NOW() FROM dx WHERE rn >= 100
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'PLUS_DI_14',  pdi, NOW() FROM dx WHERE rn >= 100
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MINUS_DI_14', ndi, NOW() FROM dx WHERE rn >= 100;

-- ─────────────────────────────────────────
-- 20. 999903 한일정밀 — 거래정지 갭 정정
--    윈도우 함수는 날짜 갭을 무시하므로 삭제 후 구간(seg)별 재계산
--    seg=1: 8~5개월 전 / seg=2: 2개월 전~어제
--    재개 후 첫 N일은 필요 행 수 미달로 지표 없음 → 정상 동작
-- ─────────────────────────────────────────
DELETE FROM TECHNICAL_INDICATOR WHERE STOCK_CODE = '999903';

-- SMA
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn FROM s),
b AS (SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, seg, rn,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  4 PRECEDING AND CURRENT ROW) AS v5,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  9 PRECEDING AND CURRENT ROW) AS v10,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS v20,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 49 PRECEDING AND CURRENT ROW) AS v50,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS v60
  FROM r)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_5',  v5,  NOW() FROM b WHERE rn >=  5 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_10', v10, NOW() FROM b WHERE rn >= 10 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_20', v20, NOW() FROM b WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_50', v50, NOW() FROM b WHERE rn >= 50 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_60', v60, NOW() FROM b WHERE rn >= 60;

-- EMA (≈ SMA 근사)
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn FROM s),
b AS (SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, seg, rn,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  4 PRECEDING AND CURRENT ROW) AS v5,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  9 PRECEDING AND CURRENT ROW) AS v10,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS v20,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS v60
  FROM r)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_5',  v5,  NOW() FROM b WHERE rn >=  5 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_10', v10, NOW() FROM b WHERE rn >= 10 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_20', v20, NOW() FROM b WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'EMA_60', v60, NOW() FROM b WHERE rn >= 60;

-- Bollinger Bands
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn FROM s),
b AS (SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, seg, rn, CLOSE_PRICE,
  AVG(CLOSE_PRICE)        OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mid,
  STDDEV_POP(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sd
  FROM r),
bb AS (SELECT *, mid+2*sd AS ub, mid-2*sd AS lb FROM b WHERE rn >= 20)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_UPPER_20',     ub,    NOW() FROM bb UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_MIDDLE_20',    mid,   NOW() FROM bb UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_LOWER_20',     lb,    NOW() FROM bb UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_PERCENT_B_20', CASE WHEN ub=lb THEN 0.5 ELSE (CLOSE_PRICE-lb)/(ub-lb) END, NOW() FROM bb UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_WIDTH_20',     ub-lb, NOW() FROM bb;

-- Stochastic %K/%D
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS l14,
  MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS h14 FROM s),
k AS (SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, seg, rn,
  CASE WHEN h14=l14 THEN 50.0 ELSE (CLOSE_PRICE-l14)/(h14-l14)*100 END AS kr FROM r),
d AS (SELECT *, AVG(kr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS dr FROM k)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_K_14_7', kr, NOW() FROM d WHERE rn >= 20 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_D_14_7', dr, NOW() FROM d WHERE rn >= 20;

-- CCI
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  (HIGH_PRICE+LOW_PRICE+CLOSE_PRICE)/3.0 AS tp FROM s),
t AS (SELECT *, AVG(tp) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS stp FROM r)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'CCI',
  (tp-stp)/NULLIF(0.015*AVG(ABS(tp-stp)) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW),0),
  NOW() FROM t WHERE rn >= 20;

-- Williams %R
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS h14,
  MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS l14 FROM s)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'WILLIAMS_R',
  CASE WHEN h14=l14 THEN -50.0 ELSE (h14-CLOSE_PRICE)/(h14-l14)*-100 END,
  NOW() FROM r WHERE rn >= 14;

-- OBV
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS pc FROM s),
sv AS (SELECT *, CASE WHEN pc IS NULL THEN 0 WHEN CLOSE_PRICE>pc THEN VOLUME WHEN CLOSE_PRICE<pc THEN -VOLUME ELSE 0 END AS sv FROM r)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'OBV',
  SUM(sv) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
  NOW() FROM sv WHERE rn >= 2;

-- Volume Ratio 20
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS pc FROM s),
t AS (SELECT *, CASE WHEN CLOSE_PRICE>pc THEN VOLUME ELSE 0 END AS u,
  CASE WHEN CLOSE_PRICE<pc THEN VOLUME ELSE 0 END AS d,
  CASE WHEN CLOSE_PRICE=pc THEN VOLUME ELSE 0 END AS e FROM r WHERE pc IS NOT NULL)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_RATIO_20', vr, NOW()
FROM (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
    (SUM(u) OVER w + SUM(e) OVER w/2.0) / NULLIF(SUM(d) OVER w + SUM(e) OVER w/2.0, 0) * 100 AS vr
  FROM t
  WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW)
) vr_t WHERE rn >= 21 AND vr IS NOT NULL;

-- Volume MA20 Ratio
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  AVG(VOLUME) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS vma FROM s)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_MA20_RATIO', VOLUME/NULLIF(vma,0), NOW() FROM r WHERE rn >= 20;

-- Gap Open
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS pc FROM s)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'GAP_OPEN', OPEN_PRICE/NULLIF(pc,0)-1.0, NOW() FROM r WHERE rn >= 2;

-- Volatility
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  LN(CLOSE_PRICE/NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE),0)) AS lr FROM s)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_5D',
  STDDEV_POP(lr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  4 PRECEDING AND CURRENT ROW), NOW() FROM r WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_20D',
  STDDEV_POP(lr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW), NOW() FROM r WHERE rn >= 21;

-- RSI
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  GREATEST(CLOSE_PRICE-LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE),0) AS gain,
  GREATEST(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE)-CLOSE_PRICE,0) AS loss FROM s),
rsi AS (SELECT *, AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  8 PRECEDING AND CURRENT ROW) AS ag9,
  AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN  8 PRECEDING AND CURRENT ROW) AS al9,
  AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS ag14,
  AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS al14
  FROM r)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_9',  CASE WHEN al9=0  THEN 100 ELSE 100-100/(1+ag9/al9)   END, NOW() FROM rsi WHERE rn >= 45 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_14', CASE WHEN al14=0 THEN 100 ELSE 100-100/(1+ag14/al14) END, NOW() FROM rsi WHERE rn >= 70;

-- ATR
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  GREATEST(HIGH_PRICE-LOW_PRICE,
    ABS(HIGH_PRICE-LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE)),
    ABS(LOW_PRICE -LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE))) AS tr FROM s)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ATR',
  AVG(tr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW),
  NOW() FROM r WHERE rn >= 70;

-- MFI
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  (HIGH_PRICE+LOW_PRICE+CLOSE_PRICE)/3.0 AS tp,
  (HIGH_PRICE+LOW_PRICE+CLOSE_PRICE)/3.0*VOLUME AS rmf,
  LAG((HIGH_PRICE+LOW_PRICE+CLOSE_PRICE)/3.0) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS ptp FROM s),
f AS (SELECT *, CASE WHEN tp>ptp THEN rmf ELSE 0 END AS pmf, CASE WHEN tp<ptp THEN rmf ELSE 0 END AS nmf FROM r WHERE ptp IS NOT NULL),
m AS (SELECT *, SUM(pmf) OVER w AS ps, SUM(nmf) OVER w AS ns FROM f WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW))
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MFI',
  CASE WHEN ns=0 AND ps=0 THEN 50.0 WHEN ns=0 THEN 100.0 ELSE 100-100/(1+ps/ns) END,
  NOW() FROM m WHERE rn >= 15;

-- MACD (seg당 130행 필요 → 두 구간 모두 해당 없음, 행 없음)
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS s12,
  AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 25 PRECEDING AND CURRENT ROW) AS s26 FROM s),
ml AS (SELECT *, s12-s26 AS macd FROM r),
ms AS (SELECT *, AVG(macd) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 8 PRECEDING AND CURRENT ROW) AS sig FROM ml)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_LINE',      macd,      NOW() FROM ms WHERE rn >= 130 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_SIGNAL',    sig,       NOW() FROM ms WHERE rn >= 130 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_HISTOGRAM', macd-sig,  NOW() FROM ms WHERE rn >= 130;

-- ADX (seg당 100행 필요 → 두 구간 모두 해당 없음, 행 없음)
INSERT INTO TECHNICAL_INDICATOR (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH s AS (SELECT *, CASE WHEN TRADE_DATE <= DATE_SUB(CURDATE(), INTERVAL 5 MONTH) THEN 1 ELSE 2 END AS seg FROM DAILY_STOCK_PRICE WHERE STOCK_CODE = '999903'),
r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS rn,
  HIGH_PRICE AS h, LOW_PRICE AS l, CLOSE_PRICE AS c,
  LAG(HIGH_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS ph,
  LAG(LOW_PRICE)   OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS pl,
  LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE) AS pc FROM s),
dm AS (SELECT *, GREATEST(h-l,ABS(h-pc),ABS(l-pc)) AS tr,
  CASE WHEN (h-ph)>(pl-l) AND (h-ph)>0 THEN h-ph ELSE 0 END AS pdm,
  CASE WHEN (pl-l)>(h-ph) AND (pl-l)>0 THEN pl-l ELSE 0 END AS ndm FROM r WHERE pc IS NOT NULL),
di AS (SELECT *, 100*AVG(pdm) OVER w/NULLIF(AVG(tr) OVER w,0) AS pdi, 100*AVG(ndm) OVER w/NULLIF(AVG(tr) OVER w,0) AS ndi FROM dm WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)),
dx AS (SELECT *, 100*ABS(pdi-ndi)/NULLIF(pdi+ndi,0) AS dx FROM di)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ADX_14',    AVG(dx) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE, seg ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), NOW() FROM dx WHERE rn >= 100 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'PLUS_DI_14',  pdi, NOW() FROM dx WHERE rn >= 100 UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MINUS_DI_14', ndi, NOW() FROM dx WHERE rn >= 100;

-- ─────────────────────────────────────────
-- 21. INDICATOR_CURSOR
--     각 종목·지표별 마지막 계산 날짜
-- ─────────────────────────────────────────
INSERT INTO INDICATOR_CURSOR (MARKET_TYPE, CODE, INDICATOR_TYPE, LAST_CALCULATED_DATE)
SELECT t.MARKET_TYPE, t.STOCK_CODE, t.INDICATOR_NAME, t.TRADE_DATE
FROM TECHNICAL_INDICATOR t
INNER JOIN (
  SELECT MARKET_TYPE, STOCK_CODE, INDICATOR_NAME, MAX(TRADE_DATE) AS TRADE_DATE
  FROM TECHNICAL_INDICATOR
  WHERE INDICATOR_NAME IN (
    'SMA_5','SMA_10','SMA_20','SMA_50','SMA_60','SMA_120','SMA_200',
    'EMA_5','EMA_10','EMA_20','EMA_60','EMA_120','EMA_200',
    'RSI_9','RSI_14','RSI_21',
    'MACD_LINE',
    'STOCHASTIC_K_14_7',
    'ADX_14',
    'BB_UPPER_20',
    'ATR',
    'OBV',
    'MFI',
    'CCI',
    'WILLIAMS_R',
    'VOLUME_RATIO_20',
    'RETURN_1D',
    'VOLATILITY_5D',
    'MA_DEVIATION_20',
    'MA5_MA20_RATIO',
    'VOLUME_MA20_RATIO',
    'GAP_OPEN'
  )
  GROUP BY MARKET_TYPE, STOCK_CODE, INDICATOR_NAME
) latest USING (MARKET_TYPE, STOCK_CODE, INDICATOR_NAME, TRADE_DATE);
