-- init_indicator_data.sql
-- TECHNICAL_INDICATOR + INDICATOR_CURSOR 시드 데이터
-- 전제: init_data.sql 이 먼저 실행되어 DAILY_STOCK_PRICE 데이터가 있어야 함
-- 제외 지표 (252행 필요): HIGH_20D_RATIO, HIGH_52W_RATIO, IS_52W_HIGH/LOW, IS_20D_HIGH/LOW
SET NAMES utf8mb4;
USE DOVE_STOCK;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE TECHNICAL_INDICATOR;
TRUNCATE TABLE INDICATOR_CURSOR;
SET FOREIGN_KEY_CHECKS = 1;

-- ─────────────────────────────────────────
-- 1. SMA (단순이동평균)
--    SMA_N: requiredDataSize = N
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4   PRECEDING AND CURRENT ROW) AS sma5,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 9   PRECEDING AND CURRENT ROW) AS sma10,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19  PRECEDING AND CURRENT ROW) AS sma20,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 49  PRECEDING AND CURRENT ROW) AS sma50,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 59  PRECEDING AND CURRENT ROW) AS sma60,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 119 PRECEDING AND CURRENT ROW) AS sma120,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 199 PRECEDING AND CURRENT ROW) AS sma200
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_5',   sma5,   NOW() FROM base WHERE rn >= 5
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_10',  sma10,  NOW() FROM base WHERE rn >= 10
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_20',  sma20,  NOW() FROM base WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_50',  sma50,  NOW() FROM base WHERE rn >= 50
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_60',  sma60,  NOW() FROM base WHERE rn >= 60
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_120', sma120, NOW() FROM base WHERE rn >= 120
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'SMA_200', sma200, NOW() FROM base WHERE rn >= 200;

-- ─────────────────────────────────────────
-- 2. Stochastic %K/%D
--    requiredDataSize = 20
--    %K = (close - MIN_LOW_14) / (MAX_HIGH_14 - MIN_LOW_14) * 100
--    %D = AVG(K, 7)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS low14,
         MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS high14
  FROM DAILY_STOCK_PRICE
),
stoch AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN high14 = low14 THEN 50.0
              ELSE (CLOSE_PRICE - low14) / (high14 - low14) * 100
         END AS k_raw
  FROM base
),
with_d AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, k_raw,
         AVG(k_raw) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS d_raw
  FROM stoch
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_K', k_raw, NOW() FROM with_d WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'STOCHASTIC_D', d_raw, NOW() FROM with_d WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 3. Bollinger Bands
--    requiredDataSize = 20
--    BB_MIDDLE = SMA20, BB_UPPER = SMA20 + 2*STDDEV20, BB_LOWER = SMA20 - 2*STDDEV20
--    BB_PERCENT_B = (close - lower) / (upper - lower)
--    BB_WIDTH = upper - lower
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         AVG(CLOSE_PRICE)        OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS mid,
         STDDEV_POP(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sd
  FROM DAILY_STOCK_PRICE
),
bb AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, CLOSE_PRICE, mid,
         mid + 2 * sd AS upper_b,
         mid - 2 * sd AS lower_b
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_UPPER',     upper_b, NOW() FROM bb WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_MIDDLE',    mid,     NOW() FROM bb WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_LOWER',     lower_b, NOW() FROM bb WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_PERCENT_B',
       CASE WHEN upper_b = lower_b THEN 0.5 ELSE (CLOSE_PRICE - lower_b) / (upper_b - lower_b) END,
       NOW() FROM bb WHERE rn >= 20
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'BB_WIDTH', upper_b - lower_b, NOW() FROM bb WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 4. CCI
--    requiredDataSize = 20
--    TP = (HIGH + LOW + CLOSE) / 3
--    CCI = (TP - SMA_TP_20) / (0.015 * mean_abs_dev_20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 AS tp
  FROM DAILY_STOCK_PRICE
),
sma_tp AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, tp,
         AVG(tp) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma_tp
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'CCI',
       (tp - sma_tp) / NULLIF(
         0.015 * AVG(ABS(tp - sma_tp)) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW),
         0
       ),
       NOW()
FROM sma_tp WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 5. Williams %R
--    requiredDataSize = 14
--    %R = (MAX_HIGH_14 - close) / (MAX_HIGH_14 - MIN_LOW_14) * -100
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         MAX(HIGH_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS high14,
         MIN(LOW_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS low14
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'WILLIAMS_R',
       CASE WHEN high14 = low14 THEN -50.0
            ELSE (high14 - CLOSE_PRICE) / (high14 - low14) * -100
       END,
       NOW()
FROM base WHERE rn >= 14;

-- ─────────────────────────────────────────
-- 6. OBV (On-Balance Volume)
--    requiredDataSize = 2
--    OBV += vol if close > prev_close, -= vol if close < prev_close, else unchanged
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         CLOSE_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
),
signed_vol AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN prev_close IS NULL THEN 0
              WHEN CLOSE_PRICE > prev_close THEN  VOLUME
              WHEN CLOSE_PRICE < prev_close THEN -VOLUME
              ELSE 0
         END AS svol
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'OBV',
       SUM(svol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
       NOW()
FROM signed_vol WHERE rn >= 2;

-- ─────────────────────────────────────────
-- 7. Volume Ratio
--    requiredDataSize = 21
--    (up_vol + unchanged_vol/2) / (down_vol + unchanged_vol/2) * 100
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         CLOSE_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
),
tagged AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN CLOSE_PRICE > prev_close THEN VOLUME ELSE 0 END AS up_vol,
         CASE WHEN CLOSE_PRICE < prev_close THEN VOLUME ELSE 0 END AS dn_vol,
         CASE WHEN CLOSE_PRICE = prev_close THEN VOLUME ELSE 0 END AS eq_vol
  FROM base WHERE prev_close IS NOT NULL
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_RATIO', vr, NOW()
FROM (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         (SUM(up_vol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW)
          + SUM(eq_vol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) / 2.0)
         / NULLIF(
             SUM(dn_vol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW)
             + SUM(eq_vol) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) / 2.0,
           0) * 100 AS vr
  FROM tagged
) t WHERE rn >= 21;

-- ─────────────────────────────────────────
-- 8. Volume MA20 Ratio
--    requiredDataSize = 20
--    volume / AVG(volume, 20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         VOLUME,
         AVG(VOLUME) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS vol_ma20
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLUME_MA20_RATIO',
       VOLUME / NULLIF(vol_ma20, 0),
       NOW()
FROM base WHERE rn >= 20;

-- ─────────────────────────────────────────
-- 9. Gap Open
--    requiredDataSize = 2
--    (open / prev_close) - 1.0
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         OPEN_PRICE,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_close
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'GAP_OPEN',
       OPEN_PRICE / NULLIF(prev_close, 0) - 1.0,
       NOW()
FROM base WHERE rn >= 2;

-- ─────────────────────────────────────────
-- 10. Returns (log return)
--     requiredDataSize = 21
--     RETURN_ND = LN(close / LAG(close, N))
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         LAG(CLOSE_PRICE, 1)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS c1,
         LAG(CLOSE_PRICE, 3)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS c3,
         LAG(CLOSE_PRICE, 5)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS c5,
         LAG(CLOSE_PRICE, 10) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS c10,
         LAG(CLOSE_PRICE, 20) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS c20
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RETURN_1D',  LN(CLOSE_PRICE / NULLIF(c1,  0)), NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RETURN_3D',  LN(CLOSE_PRICE / NULLIF(c3,  0)), NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RETURN_5D',  LN(CLOSE_PRICE / NULLIF(c5,  0)), NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RETURN_10D', LN(CLOSE_PRICE / NULLIF(c10, 0)), NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RETURN_20D', LN(CLOSE_PRICE / NULLIF(c20, 0)), NOW() FROM base WHERE rn >= 21;

-- ─────────────────────────────────────────
-- 11. Volatility (log return STDDEV)
--     requiredDataSize = 21
--     VOLATILITY_5D  = STDDEV(log daily return, 5)
--     VOLATILITY_20D = STDDEV(log daily return, 20)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         LN(CLOSE_PRICE / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE), 0)) AS log_ret
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_5D',
       STDDEV_POP(log_ret) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4  PRECEDING AND CURRENT ROW),
       NOW() FROM base WHERE rn >= 21
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'VOLATILITY_20D',
       STDDEV_POP(log_ret) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW),
       NOW() FROM base WHERE rn >= 21;

-- ─────────────────────────────────────────
-- 12. MA Deviation
--     requiredDataSize = 60
--     MA_DEVIATION_20 = (close / SMA20) - 1.0
--     MA_DEVIATION_60 = (close / SMA60) - 1.0
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         CLOSE_PRICE,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma20,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS sma60
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MA_DEVIATION_20', CLOSE_PRICE / NULLIF(sma20, 0) - 1.0, NOW() FROM base WHERE rn >= 60
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MA_DEVIATION_60', CLOSE_PRICE / NULLIF(sma60, 0) - 1.0, NOW() FROM base WHERE rn >= 60;

-- ─────────────────────────────────────────
-- 13. MA Ratio
--     requiredDataSize = 60
--     MA5_MA20_RATIO  = SMA5  / SMA20
--     MA20_MA60_RATIO = SMA20 / SMA60
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 4  PRECEDING AND CURRENT ROW) AS sma5,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS sma20,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 59 PRECEDING AND CURRENT ROW) AS sma60
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MA5_MA20_RATIO',  sma5  / NULLIF(sma20, 0), NOW() FROM base WHERE rn >= 60
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MA20_MA60_RATIO', sma20 / NULLIF(sma60, 0), NOW() FROM base WHERE rn >= 60;

-- ─────────────────────────────────────────
-- 14. RSI (SMA 근사)
--     RSI_9:  requiredDataSize = 45,  period = 9
--     RSI_14: requiredDataSize = 70,  period = 14
--     RSI_21: requiredDataSize = 105, period = 21
--     avg_gain = AVG(MAX(close-prev,0), p)
--     avg_loss = AVG(MAX(prev-close,0), p)
--     RSI = 100 - 100 / (1 + avg_gain/avg_loss)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         GREATEST(CLOSE_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE), 0) AS gain,
         GREATEST(LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) - CLOSE_PRICE, 0) AS loss
  FROM DAILY_STOCK_PRICE
),
rsi AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8  PRECEDING AND CURRENT ROW) AS ag9,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8  PRECEDING AND CURRENT ROW) AS al9,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS ag14,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW) AS al14,
         AVG(gain) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) AS ag21,
         AVG(loss) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 20 PRECEDING AND CURRENT ROW) AS al21
  FROM base
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_9',
       100 - 100 / (1 + ag9  / NULLIF(al9,  0)), NOW() FROM rsi WHERE rn >= 45
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_14',
       100 - 100 / (1 + ag14 / NULLIF(al14, 0)), NOW() FROM rsi WHERE rn >= 70
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'RSI_21',
       100 - 100 / (1 + ag21 / NULLIF(al21, 0)), NOW() FROM rsi WHERE rn >= 105;

-- ─────────────────────────────────────────
-- 15. ATR (Average True Range, SMA 근사)
--     requiredDataSize = 70
--     TR = MAX(high-low, |high-prev_close|, |low-prev_close|)
--     ATR = AVG(TR, 14)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         GREATEST(
           HIGH_PRICE - LOW_PRICE,
           ABS(HIGH_PRICE - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE)),
           ABS(LOW_PRICE  - LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE))
         ) AS tr
  FROM DAILY_STOCK_PRICE
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ATR',
       AVG(tr) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW),
       NOW()
FROM base WHERE rn >= 70;

-- ─────────────────────────────────────────
-- 16. MFI (Money Flow Index)
--     requiredDataSize = 15
--     TP = (H+L+C)/3,  RMF = TP * volume
--     pos_flow = SUM(RMF where TP > prev_TP, 14)
--     neg_flow = SUM(RMF where TP < prev_TP, 14)
--     MFI = 100 - 100 / (1 + pos_flow/neg_flow)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 AS tp,
         (HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0 * VOLUME AS rmf,
         LAG((HIGH_PRICE + LOW_PRICE + CLOSE_PRICE) / 3.0) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS prev_tp
  FROM DAILY_STOCK_PRICE
),
flows AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         CASE WHEN tp > prev_tp THEN rmf ELSE 0 END AS pos_mf,
         CASE WHEN tp < prev_tp THEN rmf ELSE 0 END AS neg_mf
  FROM base WHERE prev_tp IS NOT NULL
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MFI',
       100 - 100 / (1 +
         SUM(pos_mf) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
         / NULLIF(SUM(neg_mf) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW), 0)
       ),
       NOW()
FROM flows WHERE rn >= 15;

-- ─────────────────────────────────────────
-- 17. MACD (SMA 근사: EMA12≈SMA12, EMA26≈SMA26, signal=SMA9(MACD))
--     requiredDataSize = 130
--     MACD_LINE      = SMA12 - SMA26
--     MACD_SIGNAL    = SMA9(MACD_LINE)
--     MACD_HISTOGRAM = MACD_LINE - MACD_SIGNAL
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS sma12,
         AVG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 25 PRECEDING AND CURRENT ROW) AS sma26
  FROM DAILY_STOCK_PRICE
),
macd_line AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         sma12 - sma26 AS macd
  FROM base
),
macd_signal AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, macd,
         AVG(macd) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 8 PRECEDING AND CURRENT ROW) AS signal
  FROM macd_line
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_LINE',      macd,            NOW() FROM macd_signal WHERE rn >= 130
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_SIGNAL',    signal,          NOW() FROM macd_signal WHERE rn >= 130
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MACD_HISTOGRAM', macd - signal,   NOW() FROM macd_signal WHERE rn >= 130;

-- ─────────────────────────────────────────
-- 18. ADX / +DI / -DI (SMA 근사)
--     requiredDataSize = 100
--     TR  = MAX(H-L, |H-prevC|, |L-prevC|)
--     +DM = MAX(H - prevH, 0) if (H-prevH) > (prevL-L) else 0
--     -DM = MAX(prevL - L, 0) if (prevL-L) > (H-prevH) else 0
--     +DI = 100 * AVG(+DM,14) / AVG(TR,14)
--     -DI = 100 * AVG(-DM,14) / AVG(TR,14)
--     DX  = 100 * |+DI - -DI| / (+DI + -DI)
--     ADX = AVG(DX, 14)
-- ─────────────────────────────────────────
INSERT INTO TECHNICAL_INDICATOR
  (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME, INDICATOR_VALUE, CALCULATED_AT)
WITH base AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE,
         ROW_NUMBER() OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS rn,
         HIGH_PRICE  AS h, LOW_PRICE AS l, CLOSE_PRICE AS c,
         LAG(HIGH_PRICE)  OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS ph,
         LAG(LOW_PRICE)   OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS pl,
         LAG(CLOSE_PRICE) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE) AS pc
  FROM DAILY_STOCK_PRICE
),
dm AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         GREATEST(h - l, ABS(h - pc), ABS(l - pc)) AS tr,
         CASE WHEN (h - ph) > (pl - l) AND (h - ph) > 0 THEN h - ph ELSE 0 END AS pdm,
         CASE WHEN (pl - l) > (h - ph) AND (pl - l) > 0 THEN pl - l ELSE 0 END AS ndm
  FROM base WHERE pc IS NOT NULL
),
di AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn,
         100 * AVG(pdm) OVER w / NULLIF(AVG(tr) OVER w, 0) AS pdi,
         100 * AVG(ndm) OVER w / NULLIF(AVG(tr) OVER w, 0) AS ndi
  FROM dm
  WINDOW w AS (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW)
),
dx AS (
  SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, rn, pdi, ndi,
         100 * ABS(pdi - ndi) / NULLIF(pdi + ndi, 0) AS dx
  FROM di
)
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'ADX',
       AVG(dx) OVER (PARTITION BY MARKET_TYPE, STOCK_CODE ORDER BY TRADE_DATE ROWS BETWEEN 13 PRECEDING AND CURRENT ROW),
       NOW() FROM dx WHERE rn >= 100
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'PLUS_DI',  pdi, NOW() FROM dx WHERE rn >= 100
UNION ALL
SELECT MARKET_TYPE, STOCK_CODE, TRADE_DATE, 'MINUS_DI', ndi, NOW() FROM dx WHERE rn >= 100;

-- ─────────────────────────────────────────
-- 19. INDICATOR_CURSOR
--     각 종목·지표 타입별 마지막 계산 날짜 = 해당 종목의 마지막 TRADE_DATE
--     requiredDataSize 미달 종목·지표는 제외
--     cursorType 기준 (calculator당 1개):
--       SMA_5/10/20/50/60/120/200, RSI_9/14/21, MACD_LINE,
--       STOCHASTIC_K, ADX, BB_UPPER, ATR, OBV, MFI, CCI,
--       WILLIAMS_R, VOLUME_RATIO, RETURN_1D, VOLATILITY_5D,
--       MA_DEVIATION_20, MA5_MA20_RATIO, VOLUME_MA20_RATIO, GAP_OPEN
-- ─────────────────────────────────────────
INSERT INTO INDICATOR_CURSOR (MARKET_TYPE, CODE, INDICATOR_TYPE, LAST_CALCULATED_DATE)
SELECT t.MARKET_TYPE, t.STOCK_CODE, t.INDICATOR_NAME, t.TRADE_DATE
FROM TECHNICAL_INDICATOR t
INNER JOIN (
  SELECT MARKET_TYPE, STOCK_CODE, INDICATOR_NAME, MAX(TRADE_DATE) AS TRADE_DATE
  FROM TECHNICAL_INDICATOR
  WHERE INDICATOR_NAME IN (
    'SMA_5','SMA_10','SMA_20','SMA_50','SMA_60','SMA_120','SMA_200',
    'RSI_9','RSI_14','RSI_21',
    'MACD_LINE',
    'STOCHASTIC_K',
    'ADX',
    'BB_UPPER',
    'ATR',
    'OBV',
    'MFI',
    'CCI',
    'WILLIAMS_R',
    'VOLUME_RATIO',
    'RETURN_1D',
    'VOLATILITY_5D',
    'MA_DEVIATION_20',
    'MA5_MA20_RATIO',
    'VOLUME_MA20_RATIO',
    'GAP_OPEN'
  )
  GROUP BY MARKET_TYPE, STOCK_CODE, INDICATOR_NAME
) latest USING (MARKET_TYPE, STOCK_CODE, INDICATOR_NAME, TRADE_DATE);
