-- 데이터베이스 생성 (만약 존재하지 않는다면)
CREATE DATABASE IF NOT EXISTS DOVE_STOCK;
-- DOVE_STOCK 데이터베이스 사용
USE DOVE_STOCK;

-- 1. KRX_DAILY_DATA 테이블 생성
CREATE TABLE KRX_DAILY_DATA
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 ID',
    BASE_DATE   DATE         NOT NULL COMMENT '기준 날짜',
    MARKET_TYPE VARCHAR(20)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    RAW_DATA    JSON COMMENT '원본 JSON 데이터',
    DATA_STATUS VARCHAR(20)  NOT NULL COMMENT '데이터 처리 상태 (SUCCESS, API_FAILED 등)',
    API_CALL_AT DATE         NOT NULL COMMENT 'API 호출 날짜'
);

CREATE INDEX IDX_KRX_BASE_DATE ON KRX_DAILY_DATA (BASE_DATE);

-- 2. STOCK 테이블 생성
CREATE TABLE STOCK (
    MARKET_TYPE VARCHAR(10)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    CODE        VARCHAR(20)  NOT NULL COMMENT '주식 코드',
    NAME        VARCHAR(100) NOT NULL COMMENT '주식 이름',
    PRIMARY KEY (MARKET_TYPE, CODE)
);

-- 3. MARKET_CALENDAR 테이블 생성
CREATE TABLE MARKET_CALENDAR (
    DATE        DATE        NOT NULL COMMENT '날짜',
    MARKET_TYPE VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    DAY_TYPE    VARCHAR(20) NOT NULL COMMENT '날짜 유형 (TRADING, HOLIDAY)',
    PRIMARY KEY (DATE, MARKET_TYPE)
);

-- 4. STOCK_DATA 테이블 생성
CREATE TABLE STOCK_DATA
(
    MARKET_TYPE VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    STOCK_CODE  VARCHAR(20) NOT NULL COMMENT '주식 코드',
    TRADE_DATE  DATE        NOT NULL COMMENT '거래 날짜',
    VOLUME      BIGINT      NOT NULL COMMENT '거래량',
    OPEN_PRICE  BIGINT      NOT NULL COMMENT '시가',
    CLOSE_PRICE BIGINT      NOT NULL COMMENT '종가',
    LOW_PRICE   BIGINT      NOT NULL COMMENT '저가',
    HIGH_PRICE  BIGINT      NOT NULL COMMENT '고가',
    PRIMARY KEY (MARKET_TYPE, STOCK_CODE, TRADE_DATE)
);

-- 5. STOCK_DATA_CHANGE 테이블 생성
CREATE TABLE STOCK_DATA_CHANGE
(
    MARKET_TYPE VARCHAR(10)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    STOCK_CODE  VARCHAR(20)  NOT NULL COMMENT '주식 코드',
    TRADE_DATE  DATE         NOT NULL COMMENT '거래 날짜',
    CREATED_AT  DATETIME     NOT NULL COMMENT '생성 시각',
    PRIMARY KEY (MARKET_TYPE, STOCK_CODE, TRADE_DATE)
);

-- 6. TECHNICAL_INDICATOR 테이블 생성
CREATE TABLE TECHNICAL_INDICATOR
(
    MARKET_TYPE     VARCHAR(10)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ 등)',
    STOCK_CODE      VARCHAR(20)  NOT NULL COMMENT '주식 코드',
    TRADE_DATE      DATE         NOT NULL COMMENT '거래 날짜',
    INDICATOR_NAME  VARCHAR(30)  NOT NULL COMMENT '지표 유형 (SMA_5, EMA_12 등)',
    INDICATOR_VALUE DOUBLE       NOT NULL COMMENT '지표 값',
    CALCULATED_AT   DATETIME     NOT NULL COMMENT '계산 시각',
    PRIMARY KEY (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME)
);

-- 7. FAILED_EVENT 테이블 생성
CREATE TABLE FAILED_EVENT
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 ID',
    TOPIC         VARCHAR(100) NOT NULL COMMENT 'Kafka 토픽',
    MESSAGE_KEY   VARCHAR(255) COMMENT '메시지 키',
    PAYLOAD       TEXT         NOT NULL COMMENT '원본 메시지',
    ERROR_TYPE    VARCHAR(255) NOT NULL COMMENT '에러 타입',
    ERROR_MESSAGE TEXT         COMMENT '에러 메시지',
    LISTENER_NAME VARCHAR(255) NOT NULL COMMENT '리스너 이름',
    STATUS        VARCHAR(20)  NOT NULL COMMENT '상태 (PENDING, RESOLVED)',
    CREATED_AT    DATETIME     NOT NULL COMMENT '생성 시각'
);

CREATE INDEX IDX_FAILED_EVENT_STATUS ON FAILED_EVENT (STATUS);
