-- 데이터베이스 생성 (만약 존재하지 않는다면)
CREATE DATABASE IF NOT EXISTS DOVE_STOCK;
-- DOVE_STOCK 데이터베이스 사용
USE DOVE_STOCK;

-- 기존 테이블 제거 (의존성이 없어 순서 무관)
DROP TABLE IF EXISTS KRX_DAILY_DATA;
DROP TABLE IF EXISTS STOCK_LISTED_DATE;
DROP TABLE IF EXISTS INDICATOR_CURSOR;
DROP TABLE IF EXISTS MARKET_DATA_CURSOR;
DROP TABLE IF EXISTS MARKET_TRADING_DATE;
DROP TABLE IF EXISTS DAILY_STOCK_PRICE;
DROP TABLE IF EXISTS TECHNICAL_INDICATOR;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS FAILED_EVENT;

-- 1. KRX_DAILY_DATA — KRX API 호출 이력 (원본 JSON 응답 + 호출 상태)
CREATE TABLE KRX_DAILY_DATA
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 ID',
    BASE_DATE   DATE         NOT NULL COMMENT '기준 거래일 (yyyy-MM-dd)',
    MARKET_TYPE VARCHAR(20)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    RAW_DATA    JSON                  COMMENT '원본 JSON 응답 (성공 시에만 저장)',
    DATA_STATUS VARCHAR(20)  NOT NULL COMMENT '처리 상태 (SUCCESS / API_FAILED / API_AUTH_FAILED / BODY_NULL / BODY_ERROR / UNSUPPORTED_MARKET_TYPE)',
    API_CALL_AT DATETIME     NOT NULL COMMENT 'API 호출 일시 (yyyy-MM-dd HH:mm:ss)',
    INDEX IDX_KRX_BASE_DATE (BASE_DATE)
) COMMENT='KRX API 호출 이력 — 원본 응답과 상태를 저장';

-- 2. STOCK — 종목 마스터 (시장/코드 기본키 + 현재 거래 상태)
CREATE TABLE STOCK
(
    MARKET_TYPE    VARCHAR(10)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    CODE           VARCHAR(20)  NOT NULL COMMENT '종목 코드 (KRX ISU_CD)',
    NAME           VARCHAR(100) NOT NULL COMMENT '한글 종목명',
    TRADING_STATUS VARCHAR(20)  NOT NULL COMMENT '현재 거래 상태 (ACTIVE / SUSPENDED / DELISTED)',
    PRIMARY KEY (MARKET_TYPE, CODE),
    INDEX IDX_STOCK_TRADING_STATUS (TRADING_STATUS)
) COMMENT='종목 마스터 — 최신 상태 denormalized';

-- 3. DAILY_STOCK_PRICE — 일별 주가 (OHLCV)
CREATE TABLE DAILY_STOCK_PRICE
(
    MARKET_TYPE VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    STOCK_CODE  VARCHAR(20) NOT NULL COMMENT '종목 코드',
    TRADE_DATE  DATE        NOT NULL COMMENT '거래일 (yyyy-MM-dd)',
    VOLUME      BIGINT      NOT NULL COMMENT '거래량',
    OPEN_PRICE  BIGINT      NOT NULL COMMENT '시가',
    CLOSE_PRICE BIGINT      NOT NULL COMMENT '종가',
    LOW_PRICE   BIGINT      NOT NULL COMMENT '저가',
    HIGH_PRICE  BIGINT      NOT NULL COMMENT '고가',
    PRIMARY KEY (MARKET_TYPE, STOCK_CODE, TRADE_DATE),
    INDEX IDX_DAILY_STOCK_PRICE_MARKET_TRADE_DATE (MARKET_TYPE, TRADE_DATE)
) COMMENT='일별 주가 — 거래일의 시가/종가/고가/저가/거래량';

-- 5. STOCK_LISTED_DATE — 상장 이력 (개장일별 1:N)
CREATE TABLE STOCK_LISTED_DATE
(
    MARKET_TYPE VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    CODE        VARCHAR(20) NOT NULL COMMENT '종목 단축코드',
    DATE        DATE        NOT NULL COMMENT '상장 상태였던 개장일',
    PRIMARY KEY (MARKET_TYPE, CODE, DATE),
    INDEX IDX_STOCK_LISTED_DATE_MARKET_DATE (MARKET_TYPE, DATE)
) COMMENT='종목 상장 이력 (개장일별 1:N). 행 존재 = 해당 날짜에 상장 상태였음';

-- 5-1. MARKET_DATA_CURSOR — 시장별 종목·주가 처리 커서
CREATE TABLE MARKET_DATA_CURSOR
(
    MARKET_TYPE          VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    LAST_PROCESSED_DATE  DATE        NOT NULL COMMENT '종목·주가 처리가 완료된 마지막 날짜. 개장일·휴장일 모두 기록.',
    PRIMARY KEY (MARKET_TYPE)
) COMMENT='시장별 종목+주가 처리 커서. DailyMarketDataProcessor의 from 기준값.';

-- 5-2. MARKET_TRADING_DATE — 시장별 개장/휴장 날짜 기록
CREATE TABLE MARKET_TRADING_DATE
(
    MARKET_TYPE VARCHAR(10)  NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    TRADE_DATE  DATE         NOT NULL COMMENT '날짜',
    IS_OPEN     BOOLEAN      NOT NULL COMMENT '개장 여부 (true=개장, false=휴장)',
    PRIMARY KEY (MARKET_TYPE, TRADE_DATE)
) COMMENT='시장별 개장/휴장 날짜. DailyMarketDataService가 기록. LookbackCollector 갭 판단 기준.';

-- 6. INDICATOR_CURSOR — calculator별·종목별 기술적 지표 계산 커서
CREATE TABLE INDICATOR_CURSOR
(
    MARKET_TYPE          VARCHAR(10) NOT NULL COMMENT '시장 구분 (KOSPI/KOSDAQ/KONEX)',
    CODE                 VARCHAR(20) NOT NULL COMMENT '종목 단축코드',
    INDICATOR_TYPE       VARCHAR(30) NOT NULL COMMENT 'calculator 대표 IndicatorType (cursor 식별자)',
    LAST_CALCULATED_DATE DATE        NOT NULL COMMENT '해당 calculator가 마지막으로 평가한 날짜',
    PRIMARY KEY (MARKET_TYPE, CODE, INDICATOR_TYPE)
) COMMENT='calculator별·종목별 기술적 지표 계산 커서';

-- 7. TECHNICAL_INDICATOR — 기술적 지표 계산 결과
CREATE TABLE TECHNICAL_INDICATOR
(
    MARKET_TYPE     VARCHAR(10) NOT NULL COMMENT '시장 타입 (KOSPI, KOSDAQ, KONEX)',
    STOCK_CODE      VARCHAR(20) NOT NULL COMMENT '종목 코드',
    TRADE_DATE      DATE        NOT NULL COMMENT '거래일 (yyyy-MM-dd)',
    INDICATOR_NAME  VARCHAR(30) NOT NULL COMMENT '지표 이름 (SMA_5, EMA_12 등)',
    INDICATOR_VALUE DOUBLE      NOT NULL COMMENT '지표 값',
    CALCULATED_AT   DATETIME    NOT NULL COMMENT '계산 일시 (yyyy-MM-dd HH:mm:ss)',
    PRIMARY KEY (MARKET_TYPE, STOCK_CODE, TRADE_DATE, INDICATOR_NAME),
    INDEX IDX_TECHNICAL_INDICATOR_CALCULATED_AT (CALCULATED_AT)
) COMMENT='기술적 지표 계산 결과 — 거래일×지표 단위';

-- 8. FAILED_EVENT — 수동 검토 큐 (DLQ)
CREATE TABLE FAILED_EVENT
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 ID',
    EVENT_TYPE          VARCHAR(100) NOT NULL COMMENT 'Kafka 토픽 이름',
    EVENT_KEY           VARCHAR(255) NOT NULL COMMENT '원본 Kafka 메시지 키',
    EVENT_PAYLOAD       TEXT         NOT NULL COMMENT '원본 Kafka 메시지 값',
    REASON_CATEGORY     VARCHAR(30)  NOT NULL COMMENT '승격 사유 (AUTH_FAILED / PARSE_FAILED / RETRY_LIMIT_EXCEEDED 등)',
    LAST_ERROR_DETAIL   VARCHAR(1000)         COMMENT '실패 상세',
    ESCALATED_AT        DATETIME(6)  NOT NULL COMMENT '수동 검토 큐 등록 시각',
    UNIQUE KEY UK_FAILED_EVENT_EVENT (EVENT_TYPE, EVENT_KEY),
    INDEX IDX_FAILED_EVENT_ESCALATED_AT (ESCALATED_AT)
) COMMENT='자동 재시도 한계 초과 또는 영구 실패로 수동 개입이 필요한 이벤트 큐';
