version: '3.8'

services:
  stock-batch:
    image: stock-batch:latest
    container_name: stock-batch
    restart: unless-stopped
    environment:
      # Spring 프로파일
      SPRING_PROFILES_ACTIVE: prod

      # 데이터베이스 설정
      DB_USERNAME: dove_prod_user
      DB_PASSWORD: your_secure_password_here

      # 로그 레벨
      LOGGING_LEVEL_ROOT: info
      LOGGING_LEVEL_COM_DOVE: info

    volumes:
      - ./logs/batch:/app/logs

  stock-consumer:
    image: stock-consumer:latest
    container_name: stock-consumer
    restart: unless-stopped
    environment:
      # Spring 프로파일
      SPRING_PROFILES_ACTIVE: prod

      # 데이터베이스 설정
      DB_USERNAME: dove_prod_user
      DB_PASSWORD: your_secure_password_here

      # 로그 레벨
      LOGGING_LEVEL_ROOT: info
      LOGGING_LEVEL_COM_DOVE: info

    volumes:
      - ./logs/consumer:/app/logs