package com.dove.technicalindicator.domain.enums;

public enum IndicatorType {
    SMA_5, SMA_10, SMA_20, SMA_50, SMA_60, SMA_120, SMA_200,
    RSI_9, RSI_14, RSI_21,
    MACD_LINE, MACD_SIGNAL, MACD_HISTOGRAM,
    STOCHASTIC_K, STOCHASTIC_D,
    ADX, PLUS_DI, MINUS_DI,
    VOLUME_RATIO, OBV,
    BB_UPPER, BB_MIDDLE, BB_LOWER, BB_PERCENT_B, BB_WIDTH,
    ATR,
    MFI,
    CCI,
    WILLIAMS_R,
    RETURN_1D, RETURN_3D, RETURN_5D, RETURN_10D, RETURN_20D,
    VOLATILITY_5D, VOLATILITY_20D,
    MA_DEVIATION_20, MA_DEVIATION_60,
    MA5_MA20_RATIO, MA20_MA60_RATIO,
    HIGH_20D_RATIO, HIGH_52W_RATIO,
    VOLUME_MA20_RATIO,
    GAP_OPEN,
    IS_52W_HIGH, IS_52W_LOW, IS_20D_HIGH, IS_20D_LOW
}
